# Generated by Django 5.1.7 on 2025-03-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0004_cart_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="session_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
